### ISSUE TITLE
Doesn't follow user theming

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/net.pcsx2.PCSX2#11]
I'm not sure what else to say, it just doesn't use Adwaita dark as it probably should.

(Title bar is fine but menubar and file picker use Adwaita.)

**Comment by TingPing** [comment]
What is the output of `gsettings get org.gnome.desktop.interface gtk-theme`

I assume its wrong and you can fix it with `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`

**Comment by lionirdeadman** [comment]
That doesn't seem to fix it which is strange.. it seems to have a DBus error. :thinking: 

```bash
flatpak run --command=bash net.pcsx2.PCSX2
[📦 net.pcsx2.PCSX2 ~]$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita'
[📦 net.pcsx2.PCSX2 ~]$ gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

(process:6): dconf-WARNING **: 14:40:02.130: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by TingPing** [comment]
You can run the command on the host. Anyway new build coming where dconf works.
