### ISSUE TITLE
CDVD menu doesn't detect PS2 disc, while ddrescued image of it works

### ISSUE THREAD

**Issue by Mikaela** [flathub/net.pcsx2.PCSX2#12]
I am not sure if this is an issue with the flatpak or upstream (where I find closed https://github.com/PCSX2/pcsx2/issues/519). 

Thank you for the Flatpak, it's pleasure to use and I have played a few games without issues.

**Comment by j8r** [comment]
It is unlikely to be related to the Flatpak package. You can try with the Debian package, or build it to confirm this is an upstream issue.

**Comment by j8r** [comment]
Closing in favor of #47 and #152.
