### ISSUE TITLE
Joysticks configurable, but not usable?

### ISSUE THREAD

**Issue by Follpvosten** [flathub/net.pcsx2.PCSX2#13]
I'm running Flatpak 1.2.4 on Void Linux, using user-level installs with Flathub as the main remote.

I installed PCSX2 yesterday using the following command:

    flatpak --user install flathub net.pcsx2.PCSX2

The version I got was `1.5.0-dev`, which makes it a bit hard to duck the error, as everyone's using 1.4.0 (the stable version).

I tested playing with my keyboard at first, which worked fine, but is kinda hard to get adapted to, so I naturally want to use my game controller.

Now, the interesting issue is: With all of my gamepads (a bluetooth one, a cheap chinese USB one and an XBox USB one), while they *do* show input in the OnePad configuration window:

![Screenshot 2019-05-06 08-37-23](https://user-images.githubusercontent.com/22855787/57209975-186f9e80-6fdb-11e9-942d-5807fd1ebadc.png)

And the config also gets saved/loaded correctly, pressing any of the configured buttons doesn't do anything in-game. It just doesn't work.

Could it have to do with this being a yet-to-be-released beta version? Because if it has, I'd like to know if I can install a *stable* version of this flatpak, as it works pretty good in the basics (a bit better than the version offered by my OS, which just throws errors).

Thanks!

**Comment by Follpvosten** [comment]
I also just realized that this is a dev build from November of last year. Is it supposed to be like that? I'd think a dev branch is probably meant to have daily, or at least weekly builds.

**Comment by TingPing** [comment]
PCSX2 is one of those great projects that doesn't make releases. Feel free to bump the version though I don't expect it to be relevant.

**Comment by Mikaela** [comment]
I have updating pull request at #14.

Have you tried your gamepads outside of PCSX2? Did you run [fixcontroller.py](https://gist.github.com/dnmodder/de2df973323b7c6acf45f40dc66e8db3) after connecting your controller?

**Comment by Follpvosten** [comment]
> Have you tried your gamepads outside of PCSX2? Did you run [fixcontroller.py](https://gist.github.com/dnmodder/de2df973323b7c6acf45f40dc66e8db3) after connecting your controller?

Yes, they do work out of the box in STK, other emulators, Steam games and the OS-native PCSX2 1.4.0 (which has its own problems).

I've never heard of fixcontroller.py tho; I might try it later (it looks like its mainly targeting USB devices, whereas I would prefer my bluetooth gamepad, but I could live with that)

**Comment by j8r** [comment]
Is it fixed on the latest release for you, can you try?

**Comment by Follpvosten** [comment]
Nope, in fact it got worse - now I can't even configure any of my controllers anymore :D they still work fine everywhere else, but not in the PCSX2 flatpak.

Tried with an Xbox 360 and a PS4 controller.

Enabling and testing the rumble feature actually works, but it doesn't detect any of the gamepad's keys when I try to configure them.

**Comment by j8r** [comment]
The issue can be closes then, nothing can be done here.
cc @TingPing

**Comment by j8r** [comment]
The issue can be closed then, nothing can be done here.
cc @TingPing
