### ISSUE TITLE
USB controller not detectable if not running as root

### ISSUE THREAD

**Issue by HarpyProductions1991** [flathub/net.pcsx2.PCSX2#15]
I am running void linux
it wont detect the controller unless i run as sudo. the kde application to calibrate the controler detects every single input, from any button, trigger or stick. i would happily play it as sudo but when i do that there is no sound
here is a screen shot of kde detecting input from my gamepad
![Screenshot_20190818_232340](https://user-images.githubusercontent.com/52580369/63235500-30d19500-c229-11e9-8b5c-6b7ea3137497.png)
and here is a screenshot of pcsx2 not detecting my gamepad
![Screenshot_20190818_232449](https://user-images.githubusercontent.com/52580369/63235520-4b0b7300-c229-11e9-8d13-dc41bfadbf6e.png)

**Comment by TingPing** [comment]
Could be some permission issue on your system and the KDE app happens to work via a different method.

**Comment by HarpyProductions1991** [comment]
i had to restore a backup because i uninstalled something i should not, and when it was restored. now it started working properly.
what i uninstalled was the lxqt in order to use plamsa, i guess pcsx2 was using something that handles persmission from lxqt and when i uninstalled it to use plasma this permission handling thing must have been uninstalled too. i think its elogin or consolekit2 as i could not reboot and shutdown without root.
anyway, i will try to uninstall lxqt again and i guess i will figure out what was the thing by trial

**Comment by TingPing** [comment]
PCSX2 uses none of that, but something on your system might change permissions in `/dev` maybe.

**Comment by HarpyProductions1991** [comment]
but this exactly what handles permissions
