### ISSUE TITLE
Could not find any CD/DVD-ROM devices. Please ensure you have a drive connected and sufficient permissions to access it.

### ISSUE THREAD

**Issue by aldrinpscastro** [flathub/net.pcsx2.PCSX2#152]
When trying boot from disk, appear this mensage:
![image](https://user-images.githubusercontent.com/48888803/211231618-bb23dd78-4e30-46ff-8025-50f57c62db1e.png)
Here my version app:
PCSX2 - A Playstation 2 emulator

          ID: net.pcsx2.PCSX2
         Ref: app/net.pcsx2.PCSX2/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.3872
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 20,8?MB
     Runtime: org.kde.Platform/x86_64/6.4
         Sdk: org.kde.Sdk/x86_64/6.4

      Commit: 1e1614bce012e39773bd0339f41f60e09b3c6b644f113afd98ea37627aad0c41
      Parent: 8733e722bdfc98e9a150a9ef7eaf5fc1bc85c4bd9f9e1547d233be3ad18076cb
     Subject: Update pcsx2.git to 1.7.3872 (dae59c54)
        Date: 2023-01-08 07:26:36 +0000

**Comment by j8r** [comment]
Closing in favor of #47 , which has a similar issue.
It is a known Flatpak issue: https://github.com/flatpak/flatpak/issues/12
