### ISSUE TITLE
pcsx2-flatpak no longer compiles

### ISSUE THREAD

**Issue by Shoegzer** [flathub/net.pcsx2.PCSX2#16]
pcsx2-flatpak builds after [this](https://github.com/PCSX2/pcsx2/commit/fc35de02f25263b069c7ab4d9657d83f149b2672) upstream commit fail to compile. 
```
$ flatpak-builder builddir --arch=i386 --default-branch=stable --force-clean --install-deps-from=flathub net.pcsx2.PCSX2.json --user --install
...
CMake Error at cmake/SelectPcsx2Plugins.cmake:21 (message):
Skip build of dev9ghzdrk: missing dependencies:check these libraries ->
gtk2, pcap, libxml2
Call Stack (most recent call first):
cmake/SelectPcsx2Plugins.cmake:130 (print_dep)
CMakeLists.txt:28 (include)

-- Configuring incomplete, errors occurred!
See also "/run/build/pcsx2/CMakeFiles/CMakeOutput.log".
See also "/run/build/pcsx2/CMakeFiles/CMakeError.log".
Error: module pcsx2: Child process exited with code 1
```
[CMakeOutput.log](https://github.com/flathub/net.pcsx2.PCSX2/files/3516545/CMakeOutput.log)
[CMakeError.log](https://github.com/flathub/net.pcsx2.PCSX2/files/3516544/CMakeError.log)

Following a suggestion from @TingPing we attempted to turn off the dev9ghzdrk plugin by adding "-Ddev9ghzdrk=OFF", to the pcsx2 config-opts section of the net.pcsx2.PCSX2.json file, but the same errors are returned.

@arcum42 can you provide any thoughts or suggestions here?  Thanks.

Test system is uisng linux kernel 4.18 x64 with gcc-9.1.0.

**Comment by TingPing** [comment]
The problem is it tries to pull in GTK2 even though its built against GTK3.

**Comment by TingPing** [comment]
Hmm, `print_dep()` is meant to be fatal in package mode, but I don't see a way to disable that feature.

**Comment by Shoegzer** [comment]
@TingPing thanks for the fix.  Although, shouldn't there be a better way than not compiling the dev9 plugin?  It's not a terrible essential feature right now, but it could be in the future.  Then again this is likely to be more an upstream issue to fix.

**Comment by TingPing** [comment]
I don't know what that plugin does but looking at the build system it can never work in the sandbox as it requires elevated permissions.

**Comment by TingPing** [comment]
So the upstream issue is just that there wasn't a build flag to disable this plugin. (Or maybe I missed it)

**Comment by Shoegzer** [comment]
Interesting.  Not sure why it would require elevated perms but perhaps that's an issue that can be fixed upstream.  Also, I would think ideally it should be left enabled and the deps issue fixed upstream, though yes, at the very least there should be an option to disable.  @arcum42 your thoughts here?

**Comment by TingPing** [comment]
>  Not sure why it would require elevated perms but perhaps that's an issue that can be fixed upstream. 

It requires the capability of caputring network traffic: `sudo setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip`

I presume for debugging which isn't relevant for us.

> Also, I would think ideally it should be left enabled and the deps issue fixed upstream

That makes no sense. Its a feature that doesn't work and there is no deps issue.

**Comment by arcum42** [comment]
Most of the linux side of that plugin was done by @lowlyocean back in #2586, so he'd know more about what can be done about the permissions.

Most of what the commit referenced did was to make it print dependency messages if it didn't compile (which I didn't realise would cause packaging to fail, as when compiling normally, it just skips the plugin), and to skip the setcap command if not building the plugin.

Unfortunately, that plugin does fail to open the network adapters without it.

I had thought about moving it to extra plugins, which aren't compiled by packages by default. I could certainly add a build option to disable dev9ghzdrk. Unless you are going to be trying to play ps2 games online with pcsx2, the plugin isn't really needed.

**Comment by lowlyocean** [comment]
The plugin is for network gameplay- the capability for capturing network traffic is not for debugging. The original error in this thread is not a bug- your build machine needs gtk2, lxml2, and pcap libraries to build the plugin. The Ubuntu PPA is configured to add those libs. Can't the same be done here?

**Comment by TingPing** [comment]
Flatpak is a sandboxed format, it can never elevate permissions.

**Comment by lowlyocean** [comment]
I was curious if Wireshark (regular user software) was offered through Flatpak as it would seem to run into the same trouble. Sure enough https://github.com/flathub/org.wireshark.Wireshark/issues/4

**Comment by TingPing** [comment]
Indeed. Wireshark obviously has a valid reason to capture all network traffic on a system at least.

**Comment by Shoegzer** [comment]
Update: [this](https://github.com/PCSX2/pcsx2/commit/74e6c437f2cb1e3303fe71237f0ccb257853d804) recent upstream commit adds the option not to build the plugin.  Can such an option be added here as well vs. ignoring the compile-time errors?

**Comment by TingPing** [comment]
> Update: [this](https://github.com/PCSX2/pcsx2/commit/74e6c437f2cb1e3303fe71237f0ccb257853d804) recent upstream commit adds the option not to build the plugin. Can such an option be added here as well vs. ignoring the compile-time errors?

Done, thanks!
