### ISSUE TITLE
flatpak no longer builds

### ISSUE THREAD

**Issue by Shoegzer** [flathub/net.pcsx2.PCSX2#20]
When running the following command:

`flatpak-builder builddir --arch=i386 --default-branch=stable --force-clean --install-deps-from=flathub net.pcsx2.PCSX2.json --user --install
`

The exception is thrown:

`(flatpak-builder:5841): flatpak-builder-ERROR **: 09:56:55.498: Failed to load included manifest (/home/shoegzer/Desktop/pcsx2-flatpak/net.pcsx2.PCSX2/shared-modules/udev/udev-175.json): Failed to open file “/home/shoegzer/Desktop/pcsx2-flatpak/net.pcsx2.PCSX2/shared-modules/udev/udev-175.json”: No such file or directory
`

This is due to the recent lack of udev in shared-modules (the above command worked as of the last time I tested on October 7)

System is Linux Mint 19.2 with kernel 5.0 and flatpak 1.4.3.

**Comment by TingPing** [comment]
You updated shared-modules locally, so you update the manifest locally...

**Comment by Shoegzer** [comment]
I'm a bit confused by that, but at least I think I know what you're referring to - before running flatpak-builder, i did this:

```
$ cd shared-modules
$ git pull origin master
$ cd ..
```
This seemed to replace the contents of shared-modules with a new group of modules.  When I try running flatpak-builder without the above commands, pcsx2-flatpak compiles fine.  However, I only performed the above because you once said it was necessary to fix a compiling issue (can't recall what that was now).  Hopefully this won't be needed in the future as it no longer works, but we'll see.
