### ISSUE TITLE
Include official widescreen and no-interlacing patches from upstream distribution

### ISSUE THREAD

**Issue by Calinou** [flathub/net.pcsx2.PCSX2#220]
I've found that the Flatpak doesn't come with any widescreen and no-interlacing patches, which makes the options to load those patcheds ineffective in PCSX2's options menu until you install them yourself from https://github.com/PCSX2/pcsx2_patches.

Could this be added in the Flatpak build to match official builds? Thanks in advance :slightly_smiling_face:

**Comment by j8r** [comment]
They seems to be just downloaded to `bin/resources`, from what I can see in https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/linux_build_qt.yml.

I'll do a PR soon and let you know to test it.

**Comment by j8r** [comment]
After looking at it a bit more, you can already have them by downloading https://github.com/PCSX2/pcsx2_patches/releases/download/latest/cheats_ws.zip and https://github.com/PCSX2/pcsx2_patches/releases/download/latest/cheats_ni.zip, and extracting into `$HOME/.var/app/net.pcsx2.PCSX2/config/PCSX2`:
```sh
for cheats in cheats_ni cheats_ws; do
  wget https://github.com/PCSX2/pcsx2_patches/releases/download/latest/$cheats.zip
  unzip $cheats.zip -d $HOME/.var/app/net.pcsx2.PCSX2/config/PCSX2/$cheats
  rm $cheats.zip
done
```

If it works I can add this to the README.md and the application description. I'm not sure there is an other way. At startup PCSX2 is looking at this 2 paths.

**Comment by powerpuffboysz** [comment]
and the gameindex.yaml. having real trouble figuring out where to put it?
