### ISSUE TITLE
x64 binary not launching

### ISSUE THREAD

**Issue by Shoegzer** [flathub/net.pcsx2.PCSX2#26]
I recently ran flatpak-builder to update PCSX2 from the arch=i386 version that I had been using since November.  I now have a new binary in:

~/.local/share/flatpak/app/net.pcsx2.PCSX2/x86_64/stable/[long_string]/files/bin/PCSX2

But when I try to launch this new binary, it fails:
```
$ flatpak run --arch=x86_64 net.pcsx2.PCSX2
bwrap: execvp PCSX2: No such file or directory
```
Removing "--arch=x86_64" gives the same result.

Note that I can still launch the old i386 flatpak binary as follows:
```
~$ flatpak run --arch=i386 net.pcsx2.PCSX2
Interface is initializing.  Entering Pcsx2App::OnInit!
```
Test system is a linux mint 19.3 with kernel 5.3 and flatpak 1.7.2. 

For @Pixelnarium or @LeandroStanger since you worked on the x64 changes, wondering if either/both of you can you reproduce or otherwise might have any suggestions or help?

**Comment by Pixelnarium** [comment]
Could you please check if org.freedesktop.Platform.Compat.i386 and org.freedesktop.Platform.GL32 are installed?

**Comment by Shoegzer** [comment]
Thanks @Pixelnarium.  Those were not installed.  

When I tried installing org.freedesktop.Platform.Compat.i386 I got two options:
```
   1) runtime/org.freedesktop.Platform.Compat.i386/x86_64/18.08
   2) runtime/org.freedesktop.Platform.Compat.i386/x86_64/19.08
```
I chose option 1 since my linux mint 19.3 system is ubuntu 18.04 base, so that's closest.  I also chose to install in --user, since that's where PCSX2 is. I assume these were the right choices?

When I tried installing org.freedesktop.Platform.GL32 I got 128 options depending on nvidia driver revisions, for example the first five are:
```
   1) runtime/org.freedesktop.Platform.GL32.nvidia-430-40/x86_64/1.4
   2) runtime/org.freedesktop.Platform.GL32.nvidia-415-25/x86_64/1.4
   3) runtime/org.freedesktop.Platform.GL32.nvidia-435-17/x86_64/1.4
   4) runtime/org.freedesktop.Platform.GL32.nvidia-418-52-03/x86_64/1.4
   5) runtime/org.freedesktop.Platform.GL32.nvidia-435-27-03/x86_64/1.4
```
I assume I should choose the one corresponding to my latest driver revision?

**Comment by TingPing** [comment]
This uses 19.08. Your host doesn't matter.

**Comment by Shoegzer** [comment]
Okay, I uninstalled 18.08 and now using 19.08 instead.  

Still not sure which Platform.GL option to install though ([here](https://controlc.com/04e5f747) is a list of all 128 options).  I noticed only one option reflects my currently-installed driver rev, which is 440.82:

`  36) runtime/org.freedesktop.Platform.GL32.nvidia-440-82/x86_64/1.4`

Should I try that one?  And if that's it, then after I install org.freedesktop.Platform.GL32, will it update whenever my host graphics driver updates or should I maintain it manually?  

Thanks for your help.

**Comment by TingPing** [comment]
You don't need to install anything else.

**Comment by Shoegzer** [comment]
Yes, and again here's what I have:
```
$ flatpak --gl-drivers
nvidia-440-82
default
host
```
So I installed these two:
```
i386	        org.freedesktop.Platform.Compat.i386		        19.08	x86_64	flathub	user
nvidia-440-82	org.freedesktop.Platform.GL32.nvidia-440-82		1.4	x86_64	flathub	user
```
I'm getting further now, and PCSX2 launches, but when I attempt to launch a title, I get a popup message indicating:

`GS plugin failed to open.  Your computer may have insufficient resources, or incompatible hardware/drivers.`

Is there something else I need to install?

**Comment by Shoegzer** [comment]
Update: One other point to note in case it helps - when I had first started the new x86_64 pcsx2, it threw the following exception:

![pic](https://user-images.githubusercontent.com/12475371/81748767-65047a00-9478-11ea-8a09-20f372b4cd76.png)

Looking further into the plugin panel I see this:
![pic2](https://user-images.githubusercontent.com/12475371/81748863-954c1880-9478-11ea-9e74-6ab3ded15932.png)

I noticed that the reference at the bottom of the screen to "/app/lib32/pcsx2" (even though it is greyed out).  Is this correct?  I'm just wondering if it's erroneously using the plugins from my older i386 pcsx2 install rather than the newer x86_64 one.

**Comment by TingPing** [comment]
>  I'm just wondering if it's erroneously using the plugins from my older i386 pcsx2 install rather than the newer x86_64 one.

Again not how flatpak works at all. Only the one application exists in the sandbox.

**Comment by TingPing** [comment]
Does the warning go away after first launch?

**Comment by Shoegzer** [comment]
Yes.

**Comment by TingPing** [comment]
So everything works then and this can be closed?

**Comment by Shoegzer** [comment]
I thought you meant the warning about the configured pluigin being not found (as I mentioned it only appeared when I started pcsx2 for the first time).  I still can't launch titles, when I attempt to, I get the "GS plugin failed to open" error as noted above.

**Comment by Pixelnarium** [comment]
Same as in the other issue: Could you please try the other GS plugins that are available just to have this tested? Additionaly: Could you please move ~/.var/app/net.pcsx2.PCSX2 to another backup location to get a fresh one on the next start?

**Comment by Shoegzer** [comment]
Thanks @Pixelnarium.  I've also moved that folder to a backup location, launched PCSX2 as if a fresh install, and tried again with a title, but it threw the "GS plugin failed to open..." exception.  This occurs with each of the three GL plugin options available.

Also in the interest of streamlining our troubleshooting efforts, perhaps we close this issue and report results in #27 since my observations seem identical to @Nightmayr?  Just let me know whatever you feel is best.
