### ISSUE TITLE
GS Plugin failed to open

### ISSUE THREAD

**Issue by Nightmayr** [flathub/net.pcsx2.PCSX2#27]
Hi, I just performed a fresh install of the flatpak from flathub to get PCSX2 version 1.6.0, however upon trying to launch an ISO the app throws an error in the log, `GS plugin failed to open! (thread:MTGS) (thread:EE Core)`. When launching the ISO a dialog box appears saying **GS Plugin failed to open. Your computer may have insufficient resources, or incompatible hardware/drivers.**

PCSX2 program log:
```
Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
Closing plugins...
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
(p) GS plugin failed to open!(thread:MTGS)(thread:EE Core)
```

System specs: 
OS: Ubuntu 20.04
CPU: AMD Ryzen 9 3950x
GPU: GeForce RTX2080Ti (Driver 440.64)

Many thanks for providing the flatpak

**Comment by Pixelnarium** [comment]
Could you please check if org.freedesktop.Platform.Compat.i386 and org.freedesktop.Platform.GL32 are installed? Maybe slightly the same as https://github.com/flathub/net.pcsx2.PCSX2/issues/26

**Comment by Nightmayr** [comment]
I do appear to have both those components installed,

output of `flatpak list | grep Compat` 
`i386	org.freedesktop.Platform.Compat.i386		19.08	x86_64	flathub	system`
outut of `flatpak list | grep GL32`
`default	org.freedesktop.Platform.GL32.default		19.08	x86_64	flathub	system`

**Comment by Pixelnarium** [comment]
I think there are multiple GS plugins. Could be please try the other ones? I currently have no PC with an Nvidia GPU so I have to guess.

**Comment by Shoegzer** [comment]
For ease of reference:

I tested the three GS plugins available with the same result ("GS plugin failed to open").

Test system is linux mint 19.3 with kernel 5.3, flatpak 1.7.2, Nvidia gtx 1070M card with nvidia 440.82 drivers.  Testing against commit 114ec2eab6c639bf6ba79af565951278eda2163e

**Comment by Pixelnarium** [comment]
I think I found the issue. PR created.

**Comment by Nightmayr** [comment]
Thanks @Pixelnarium, I can confirm the PR did the trick with recognising my nvidia driver, allowing me to launch titles
