### ISSUE TITLE
Rebuild with DISABLE_ADVANCE_SIMD=TRUE

### ISSUE THREAD

**Issue by wine** [flathub/net.pcsx2.PCSX2#3]
Hello. On some CPUs, the flathub build crashes at startup with `invalid opcode` as reported in #1 

Adding the `DISABLE_ADVANCE_SIMD=TRUE` build option should solve that. Check these links:

https://pcsx2.net/266-linux-news.html
https://bugs.archlinux.org/task/43796
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pcsx2
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/pcsx2/template

I think that a flatpak package should be compatible as much as possible. If you are worried about performance drops on currently supported CPUs, maybe you can consider creating a separate package?

Thank you.

**Comment by TingPing** [comment]
Seems reasonable, mind submitting a PR?
