### ISSUE TITLE
Problems with vsync in latest dev version

### ISSUE THREAD

**Issue by Elserjo** [flathub/net.pcsx2.PCSX2#42]
First of all, thank you for creating and supporting flatpak package. 

Does anyone has problems with vsync on latest dev version? I have screen tearing on version 1.7.2078 (25th of November) when i playing Silent Hill 2.

PCSX2 Settings:

Render: OpenGL
Interlacing: Blend ttf
Texture Filtering: Bilinear (Forced)

Downgrade to 1.7.0 1280 (26th September) have solved problem (with same settings).

My videocard: Nvidia GTX 1070 
Driver version: nvidia-495-44
Kernel: 5.10.74-gentoo

**Comment by j8r** [comment]
I doubt this comes from the Flatpak itself, since it was not happening before.

To be sure you can compile the program from source, then open an issue at https://github.com/PCSX2/pcsx2/issues.

**Comment by j8r** [comment]
@Elserjo Unlikely related to Flatpak, because a downgrade of the application solved the issue.
I suggest to close @TingPing
