### ISSUE TITLE
First Time Configuration "Configuration Guide" and "Readme / FAQ" links don't work

### ISSUE THREAD

**Issue by skierpage** [flathub/net.pcsx2.PCSX2#48]
The first time running the PCSX2 flatpak, a "PCSX2 First Time Configuration" dialog appears with suggestions to read, and links to, "Configuration Guide" and "Readme / FAQ". But the links don't work, and if you run from the command line, the errors
```
Failed to open '/app/share/doc/Pcsx2/Configuration_Guide.pdf': No such file or directory
Failed to open '/app/share/doc/Pcsx2/PCSX2_FAQ.pdf': No such file or directory
```
appear.

I believe the PCSX2 build creates these, see https://github.com/PCSX2/pcsx2/tree/master/pcsx2/Docs , so the fix may be to build the docs and copy the PDF files to an /app/share/doc directory. However, I'm not sure if passing these paths to your PC's PDF handler will work, they may only be meaningful in the flatpak's environment.

As a workaround, you can read the markup on GitHub for the same content at
- [Configuration Guide](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Docs/Configuration_Guide/Configuration_Guide.md)
- [Readme / FAQ](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Docs/PCSX2_FAQ.md)

**Comment by j8r** [comment]
PCSX2 Qt no longer shows this. Parts of this documentations are now outdated.
