### ISSUE TITLE
GDK assertion fails and hangs when opening general settings

### ISSUE THREAD

**Issue by jclc** [flathub/net.pcsx2.PCSX2#55]
Filed an issue in the main repository but this might be a Flatpak issue.

https://github.com/PCSX2/pcsx2/issues/5977

![image](https://user-images.githubusercontent.com/10243558/165441038-88ec2376-49ba-43b1-b04f-7ccabec67e74.png)

No other useful log messages or printfs

**Comment by tellowkrinkle** [comment]
PCSX2 was having a similar issue with its appimage, which was fixed by PCSX2/pcsx2#5935

**Comment by j8r** [comment]
Is it fixed for you now?

**Comment by jclc** [comment]
The Flatpak version seems to run fine now.
