### ISSUE TITLE
Wayland support (At least for Nvidia)

### ISSUE THREAD

**Issue by Bitwolfies** [flathub/net.pcsx2.PCSX2#63]
While Wayland support (At least for Nvidia) is not great with PCSX2, it at least *works* on the appimage, on the flatpack, this error is displayed in Wayland mode when launching any game, in Vullkan or OpenGL
![Screenshot_20220731_133108](https://user-images.githubusercontent.com/65789901/182044152-a2f5587c-114f-4639-8e7e-302265bd9e57.png)
 I enabled logs, but this bug produces none.

**Comment by j8r** [comment]
The wayland permissions are not given in the flatpak.
Can you add them with Flatseal, or the command line, and test of it works for you?

**Comment by j8r** [comment]
The wayland permissions are not given in the flatpak.
Can you add `socket=wayland` with Flatseal, or the command line, and test if it works for you?

**Comment by Bitwolfies** [comment]
> The wayland permissions are not given in the flatpak. Can you add `socket=wayland` with Flatseal, or the command line, and test if it works for you?

Sorry, I should have specifed, this issue only happens when I give it wayland permissisons with flatseal, and remove its xorg ones. It works alright in Xwayland mode.

**Comment by j8r** [comment]
I've enabled Wayland support, works with my Radeon RX 550.

**Comment by j8r** [comment]
Closing the issue, I doubt we can do anything more on the packaging side.
