### ISSUE TITLE
Flatpak version now years behind latest source

### ISSUE THREAD

**Issue by Shoegzer** [flathub/net.pcsx2.PCSX2#9]
This is just a request to modernize the flatpak.  I assume the flatpak is tied to stable major releases but nevertheless, with no official 1.5.0 release in sight, and the fact that 1.4.0 is now years behind, is there any chance of a mid-release update, to include the latest plug-ins etc?  It could always be updated once more if/when the official 1.5.0 release is ever released.

The flatpak is now the only way to even use pcsx2 on certain distros given major conflicts with i386 dependencies which didn't previously exist (see [here](https://github.com/PCSX2/pcsx2/issues/2666))
 
@TingPing thank you for any help you may offer here.

**Comment by TingPing** [comment]
Because they are one of those great projects that just gave up on making releases...

**Comment by Shoegzer** [comment]
@TingPing Thank you so much!  This updated just fine.
