### ISSUE TITLE
Enable network permission

### ISSUE THREAD

**Issue by Leuug** [flathub/net.pcsx2.PCSX2#97]
PCSX2 has an achievements feature, to use this you need to login to "retroachievements.org". But the users can't login to this site if they don't have the network permission enabled in the flatpak.

Most people don't know that the problem is that they don't have network permission and how the change the permission by them selves, they end up thinking that this is an issue with the application instead of the flatpak.

**Comment by j8r** [comment]
Will also fix the thumbnails download feature.
